### ISSUE TITLE
[Suggestion] Wand mode for a reappearing wall

### ISSUE THREAD

**Issue by Ultimushadow** [LCLPYT/illusory-walls#1]
Hey there, absolutely love the mod, I found one thing to be a bit tedious though and that is replacing a wall after it's been hit
Now tbh it's entirely possible I've missed something and if so, my apologies, but the method I found works is to use a command to set all the blocks back and a command to spawn a wall back in its position with all the block details, which is pretty inefficient if you're using multiple walls, a large number of different blocks, or if you're trying to avoid command blocks

Personally, I think a wand mode that sets a wall to be only temporarily disable would be best! The functionality would be as follows:
When shift+right clicked in the air, the wand will enter "multi-use" mode (rather than "single-use" mode which is what the default would be renamed to). When holding the multi-use mode wand and shifting, using your scroll wheel would increase or decrease the duration in seconds, from 1 up to 10, then increase by tens until 60, at which point it would transition to minutes (same deal, 1-10, 10-60). This transition would make it easier for the user so they don't have to scroll all the way until 3600 or something. An alternative way to set the time (arguably easier) would be to right click the air, open a gui, and have a number input and a seconds/minutes/hours selection. Either way, this allows the user to decide which walls come back, when they come back, and if they come back at a different rate than other walls.

The next step of this would be the walls themselves, which would get a new tag called "resetTime" or something similar. This would inherit the time in ticks from the wand, and when broken, instead of removing the blocks and fading and then being removed, it would remove the blocks, fade, and remain at the last stage of the fade animation while the timer ticks down. Once the timer hits zero, the wall could reverse the fade animation, and using the blocks stored in it's nbt, replace the wall, finally resetting the timer and it's as if it was never touched! 

Personally I would see great usage out of this, and for those of us who will be using this on servers where multiple people could potentially be activating it for things that have individual runs and need to be reset, it would help immensely!
Let me know what you think, and if this is within the scope of the mod!

**Comment by LCLPYT** [comment]
Hi Ultimushadow,
thank you for your suggestion. I've had a similar idea a while ago.
I like your idea of configuring the respawn duration by scrolling. However, I also think it is easier to just open a GUI, especially because it is more extensible.

This is definitely going onto my todo-list! I will leave a ping here, when there are any updates!

PS: Your suggestion is very well written, thank you for getting into detail that much. I appreciate it 👍

**Comment by Ultimushadow** [comment]
A ping would be appreciated, thank you for looking into it! 

And of course, modders all too often get really repetitive suggestions about "update this version" or "make it work with this mod", glad my clarity can help!

**Comment by LCLPYT** [comment]
@Ultimushadow After a far to long delay, I have finally managed to implement the reappearing wall.

If you are using the latest version, you can Shift+Right Click on an illusory wall to edit its properties.
You can also configure your defaults by Shift+Right Clicking in the air.
In the screen that pops up, you can edit whether the wall should respawn or not.
You can also adjust the cooldown individually.

You can download the latest version [here](https://modrinth.com/mod/illusory-walls/version/0.2.0+1.20).

Thank you for your suggestion!
