### ISSUE TITLE
Cannot punch wall in adventure mode

### ISSUE THREAD

**Issue by EvelinTheAriral** [LCLPYT/illusory-walls#2]
As the title says, punching an illusory wall in adventure mode doesn't make it go away.

**Comment by LCLPYT** [comment]
Thanks for letting me know.
Unfortunately, I don't really have time to work on the project right now.

This will be fixed in the next release.
I will leave a message when it is released.

**Comment by LCLPYT** [comment]
Fixed in version 0.2.0
