### ISSUE TITLE
Can't drop items by dragging them out of inventory, only droppable by pressing drop keybind

### ISSUE THREAD

**Issue by zukitbh** [LCLPYT/illusory-walls#7]
Whenever I try to drop an item by click and dragging out of inventory, it disappears momentarily, but on closing inventory, it returns to the hotbar. Removed mod, tested drag and drop, can drop items. Re-added mod, tested again, can no longer drop items by click and drag.

Resulting console log from this: 

> [06/16/2024 08:25:30 AM] 	at java.base/java.util.Arrays$ArrayList.get(Arrays.java:4266)
> [06/16/2024 08:25:30 AM] 	at net.minecraft.class_2371.get(class_2371.java:47)
> [06/16/2024 08:25:30 AM] 	at net.minecraft.class_1661.method_5438(class_1661.java:484)
> [06/16/2024 08:25:30 AM] 	at work.lclpnet.illwalls.event.ModEventListener.lambda$registerStaffHeldEvents$9(ModEventListener.java:147)
> [06/16/2024 08:25:30 AM] 	at work.lclpnet.kibu.hook.player.PlayerInventoryHooks.lambda$static$2(PlayerInventoryHooks.java:38)
> [06/16/2024 08:25:30 AM] 	at work.lclpnet.kibu.hook.KibuHooks.lambda$onInitialize$3(KibuHooks.java:64)
> [06/16/2024 08:25:30 AM] 	at work.lclpnet.kibu.hook.player.PlayerInventoryHooks.lambda$static$14(PlayerInventoryHooks.java:106)
> [06/16/2024 08:25:30 AM] 	at net.minecraft.class_3244.handler$chl000$kibu-hooks$kibu$onClickSlot(class_3244.java:3614)
> [06/16/2024 08:25:30 AM] 	at net.minecraft.class_3244.method_12076(class_3244.java:1710)
> [06/16/2024 08:25:30 AM] 	at net.minecraft.class_2813.method_12191(class_2813.java:71)
> [06/16/2024 08:25:30 AM] 	at net.minecraft.class_2813.method_11054(class_2813.java:14)
> [06/16/2024 08:25:30 AM] 	at net.minecraft.class_2600.method_11072(class_2600.java:27)
> [06/16/2024 08:25:30 AM] 	at net.minecraft.class_3738.run(class_3738.java:18)
> [06/16/2024 08:25:30 AM] 	at net.minecraft.class_1255.method_18859(class_1255.java:162)
> [06/16/2024 08:25:30 AM] 	at net.minecraft.class_4093.method_18859(class_4093.java:23)
> [06/16/2024 08:25:30 AM] 	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864)
> [06/16/2024 08:25:30 AM] 	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173)
> [06/16/2024 08:25:30 AM] 	at net.minecraft.class_1255.method_16075(class_1255.java:136)
> [06/16/2024 08:25:30 AM] 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846)
> [06/16/2024 08:25:30 AM] 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840)
> [06/16/2024 08:25:30 AM] 	at net.minecraft.class_1255.method_5383(class_1255.java:121)
> [06/16/2024 08:25:30 AM] 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:814)
> [06/16/2024 08:25:30 AM] 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702)
> [06/16/2024 08:25:30 AM] 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
> [06/16/2024 08:25:30 AM] 	at java.base/java.lang.Thread.run(Thread.java:1583)
> [06/16/2024 08:25:30 AM] [Server thread/ERROR] Failed to handle packet net.minecraft.class_2813@90603c4, suppressing error

Recorded dropping items with drop button from hotbar (Q) 2x, then drag and drop 2x

With mod **enabled**:

https://github.com/LCLPYT/illusory-walls/assets/142580729/5192311b-eeb7-4a33-bd64-be76358974fa

Now with the mod **disabled**: 

![image](https://github.com/LCLPYT/illusory-walls/assets/142580729/2b5cdb36-aafe-4fdc-8c68-4f21bb482f72)

https://github.com/LCLPYT/illusory-walls/assets/142580729/32dcf32a-7568-470c-bdbd-0498f41f3173

**Comment by LCLPYT** [comment]
Thank you for the bug report! 
This is now fixed in version 0.2.1 for Minecraft 1.21, 1.20.6 and 1.20.4: https://modrinth.com/mod/illusory-walls/versions
